# -*- coding: utf-8 -*-
"""Predicting Iris Species using Machine Learning

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ikp-4kr0pxaCYUv_Aq5fxjwLPHmykDPm
"""

from sklearn.datasets import load_iris
import pandas as pd

# Load the dataset
iris = load_iris()
X = iris.data # Features
y = iris.target # Labels

# Create a DataFrame for better viewing
df = pd.DataFrame(X, columns=iris.feature_names)
df['species'] = y
print(df.head())
print(df.describe())

from sklearn.model_selection import train_test_split

# Split the data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"Training set size: {X_train.shape[0]} samples")
print(f"Testing set size: {X_test.shape[0]} samples")

from sklearn.svm import SVC

# Choose a model (Support Vector Classifier)
model = SVC(kernel='linear')

# Train the model
model.fit(X_train, y_train)

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Make predictions on the test data
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")

# Detailed report
print("\nClassification Report:")
print(classification_report(y_test, y_pred, target_names=iris.target_names))

# Confusion Matrix
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

# Example of a new flower's measurements
# Let's say we have a sepal length of 5.1, sepal width of 3.5, petal length of 1.4, and petal width of 0.2
new_flower_measurements = [[5.1, 3.5, 1.4, 0.2]]

# Make a prediction
prediction = model.predict(new_flower_measurements)

# Get the predicted species name
predicted_species = iris.target_names[prediction[0]]
print(f"\nPredicted species for the new flower: {predicted_species}")